version: '3.8'

services:
  backend:
    image: python:3.12.3
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    environment:
      - PATH=${POETRY_HOME}/bin:$PATH
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    depends_on:
      - db

  frontend:
    image: node:20.13.1
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    env_file:
      - ./.env
    command: npm start
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  postgres_data:
